name: Create baseline environment.

on:
  workflow_dispatch:
    inputs:    
     env_name:
        description: name for the environment to be created
        required: true

     user_id:
        description: AAD object id for the user
        required: true
   
 #Do Not change these values
      

jobs:
  Create-Environments:
    runs-on: ubuntu-latest
    # or you can say runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}        
        
    - name: Create Environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        name: ${{ github.event.inputs.env_name}}
        type: Production
        domain: ${{ github.event.inputs.env_name}}
    
    - name: assign-user to environment
      uses:  microsoft/powerplatform-actions/assign-user@v0
      with:
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        environment: 'https://${{ github.event.inputs.env_name}}.dynamics.com'
        user: ${{ github.event.inputs.user_id }}
        role: System Administrator
        
    